name: water_tank_app
description: تطبيق شركة البرعي للمياه
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  firebase_core: ^4.14.0
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  connectivity_plus: ^6.0.0
  url_launcher: ^6.2.1
  crypto: ^3.0.3
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  path: ^1.9.1
  file_picker: ^12.2.0
  flutter_contacts: ^2.3.1
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
